Repository SE701Group3/se701-assignment1, pull requests merged in 2020-03, with the labels that each got.

#20 Setup/routing
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.js
  frontend/src/pages/CreatePost/index.jsx
  frontend/src/pages/Frontpage/index.jsx
  frontend/src/pages/PostDetail/index.jsx
  frontend/src/routes/routes.jsx
Labels: enhancement, frontend

#22 Issue/#6 Create a continuous deployment pipeline
  .github/workflows/cd_frontend.yml
  .github/workflows/cd_server.yml
Labels: enhancement

#25 Issue/#24 Lint the frontend code with airbnb style during build step
  frontend/.eslintrc
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.js
  frontend/src/pages/CreatePost/index.jsx
  frontend/src/pages/Frontpage/index.jsx
  frontend/src/pages/PostDetail/index.jsx
  frontend/src/routes/routes.jsx
  frontend/src/serviceWorker.js
Labels: documentation, enhancement, frontend

#34 Issue/#31 Set up Jest unit tests
  server/app.js
  server/jest-mongodb-config.js
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/db/index.js
  server/src/db/models/post.js
  server/src/routes/posts.js
  server/test/integration/post.spec.js
  server/test/model/post.spec.js
Labels: backend, enhancement

#47 Issue/#39 Create REACT component of the createnewpost page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/CreatePost/CreatePost.module.css
  frontend/src/pages/CreatePost/CreatePostModal.jsx
  frontend/src/pages/CreatePost/index.jsx
Labels: enhancement, frontend

#37 Issue/#36 Set up linter for the backend
  server/.eslintrc.js
  server/.prettierrc.js
  server/app.js
  server/jest-mongodb-config.js
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/db/index.js
  server/src/db/models/post.js
  server/src/routes/posts.js
  server/test/integration/post.spec.js
  server/test/model/post.spec.js
Labels: backend, documentation, enhancement

#40 Issue/#38 Implement CreatePostContainer and service
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/CreatePost/CreatePostModal.jsx
  frontend/src/pages/CreatePost/index.jsx
  frontend/src/pages/CreatePost/withCreatePostService.jsx
  frontend/src/pages/CreatePost/withCreatePostService.test.js
  frontend/src/services/createPostService.js
  frontend/src/services/createPostService.test.js
  frontend/src/setupTests.js
Labels: enhancement, frontend

#45 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#46 Issue/#26 Add basic README
  README.md
Labels: documentation

#53 Issue/#50 update mongoose post schema
  server/package-lock.json
  server/src/db/models/post.js
  server/src/routes/posts.js
  server/test/integration/post.spec.js
  server/test/model/post.spec.js
Labels: backend

#52 Issue #32 Feature/frontpage container
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.test.js
  frontend/src/common/Header/Header.jsx
  frontend/src/common/Header/Header.module.css
  frontend/src/common/icons/clap.png
  frontend/src/common/icons/emoji.png
  frontend/src/common/icons/hyperlink.png
  frontend/src/common/icons/logo.png
  frontend/src/common/icons/photo.png
  frontend/src/common/icons/sad.png
  frontend/src/pages/CreatePost/index.jsx
  frontend/src/pages/CreatePost/withCreatePostService.jsx
  frontend/src/pages/CreatePost/withCreatePostService.test.js
  frontend/src/pages/Frontpage/FrontpageContainer.jsx
  frontend/src/pages/Frontpage/Post.jsx
  frontend/src/pages/Frontpage/Post.module.css
  frontend/src/pages/Frontpage/frontpage.jsx
  frontend/src/pages/Frontpage/frontpageStyles.module.css
  frontend/src/pages/Frontpage/index.jsx
  frontend/src/routes/routes.jsx
  frontend/src/services/frontpageService.jsx
Labels: frontend

#56 Issue #42 Adding initial class files
  frontend/src/pages/PostDetail/CommentsContainer.jsx
  frontend/src/pages/PostDetail/CreateCommentModal.jsx
  frontend/src/pages/PostDetail/PostDetail.jsx
  frontend/src/pages/PostDetail/index.jsx
Labels: enhancement, frontend

#59 Fix wiki link in README
  README.md
Labels: documentation

#58 Issue/#39 style new thread modal
  frontend/src/pages/CreatePost/CreatePost.module.css
  frontend/src/pages/CreatePost/CreatePostModal.jsx
  frontend/src/pages/CreatePost/withCreatePostService.jsx
Labels: enhancement, frontend

#66 Adding comment container to Post-Detail page
  frontend/src/pages/PostDetail/Comment.jsx
  frontend/src/pages/PostDetail/Comment.module.css
  frontend/src/pages/PostDetail/CommentsContainer.jsx
  frontend/src/pages/PostDetail/PostDetailPage.jsx
  frontend/src/pages/PostDetail/PostDetailPageContainer.jsx
  frontend/src/pages/PostDetail/index.jsx
  frontend/src/services/PostDetailService.js
Labels: approved, enhancement, frontend

#63 implemented delete route and unit tests
  server/src/routes/posts.js
  server/test/integration/post.spec.js
Labels: backend

#76 issue #74/75 postdetails page original post and nav bar
  frontend/src/pages/PostDetail/PostDetail.jsx
  frontend/src/pages/PostDetail/PostDetailPage.jsx
  frontend/src/pages/PostDetail/PostDetailPageContainer.jsx
  frontend/src/services/PostDetailService.js
Labels: seeking-approval

#77 Link comment modal
  frontend/src/common/icons/reply.png
  frontend/src/pages/PostDetail/Comment.jsx
  frontend/src/pages/PostDetail/Comment.module.css
  frontend/src/pages/PostDetail/CreateCommentModal.jsx
  frontend/src/pages/PostDetail/PostDetailPage.jsx
  frontend/src/pages/PostDetail/PostDetailPageContainer.jsx
  frontend/src/pages/PostDetail/withCreateCommentService.jsx
  frontend/src/services/PostDetailService.js
  frontend/src/services/createPostService.test.js
Labels: enhancement, frontend

#83 Fix post detail
  frontend/src/pages/PostDetail/PostDetail.jsx
  frontend/src/pages/PostDetail/PostDetailPage.jsx
  frontend/src/pages/PostDetail/PostDetailPageContainer.jsx
Labels: enhancement, frontend

#88 Fixed bug where code can't handle multiple comments
  server/src/routes/posts.js
  server/test/integration/post.spec.js
Labels: backend, bug

#102 Change backend to reflect specification
  server/app.js
  server/src/db/models/comments.js
  server/src/db/models/post.js
  server/src/routes/posts.js
  server/test/integration/post.spec.js
  server/test/model/post.spec.js
Labels: backend

#109 Add documentation to the Post-Detail Page components
  frontend/src/pages/Frontpage/index.jsx
  frontend/src/pages/PostDetail/PostDetailPage.jsx
  frontend/src/pages/PostDetail/PostDetailPageContainer.jsx
  frontend/src/pages/PostDetail/index.jsx
  frontend/src/pages/PostDetail/withCreateCommentService.jsx
  frontend/src/services/postDetailService.js
Labels: enhancement, frontend

#110 Implement unit tests
  server/src/routes/posts.js
  server/test/integration/post.spec.js
  server/test/model/post.spec.js
Labels: backend, bug
